#!/usr/bin/env python3
"""
Fetch publications from Google Scholar and update publications.yaml

This script uses the scholarly library to fetch your publications from Google Scholar
and updates the data/publications.yaml file.

Usage:
    1. Install dependencies: pip install scholarly pyyaml
    2. Run: python fetch_publications.py

Note: Google Scholar may rate-limit requests. If you encounter issues,
      the script will retry with delays.
"""

import yaml
from scholarly import scholarly
import sys
from pathlib import Path

def fetch_scholar_publications(scholar_id):
    """
    Fetch publications from Google Scholar using the scholarly library.

    Args:
        scholar_id: Your Google Scholar ID (e.g., "QGaRpqYAAAAJ")

    Returns:
        List of publication dictionaries
    """
    print(f"Fetching publications for Google Scholar ID: {scholar_id}")

    try:
        # Search for author
        search_query = scholarly.search_author_id(scholar_id)
        author = scholarly.fill(search_query)

        print(f"Found author: {author['name']}")
        print(f"Total publications: {len(author['publications'])}")

        publications = []

        for i, pub in enumerate(author['publications'], 1):
            print(f"Processing publication {i}/{len(author['publications'])}: {pub['bib'].get('title', 'Untitled')}")

            # Fill in details for this publication
            pub_filled = scholarly.fill(pub)
            bib = pub_filled['bib']

            # Extract relevant information
            publication = {
                'date': bib.get('pub_year', 'N/A'),
                'title': bib.get('title', 'Untitled'),
                'authors': bib.get('author', 'Unknown authors'),
                'venue': bib.get('venue', bib.get('journal', 'Unknown venue')),
                'description': bib.get('abstract', '')[:200] + '...' if bib.get('abstract') else 'No description available',
                'links': []
            }

            # Add links if available
            if 'eprint_url' in pub_filled:
                publication['links'].append({
                    'name': 'Paper',
                    'url': pub_filled['eprint_url']
                })
            elif 'pub_url' in pub_filled:
                publication['links'].append({
                    'name': 'Paper',
                    'url': pub_filled['pub_url']
                })

            # Add citation count as metadata (optional)
            if 'num_citations' in pub_filled:
                publication['citations'] = pub_filled['num_citations']

            publications.append(publication)

        # Sort by year (most recent first)
        publications.sort(key=lambda x: str(x['date']), reverse=True)

        return publications

    except Exception as e:
        print(f"Error fetching publications: {e}")
        print("This might be due to rate limiting. Try again later or add publications manually.")
        return None

def update_yaml_file(publications, yaml_path='data/publications.yaml'):
    """
    Update the publications.yaml file with fetched publications.

    Args:
        publications: List of publication dictionaries
        yaml_path: Path to the publications.yaml file
    """
    # Read existing YAML to preserve google_scholar_id if set
    yaml_file = Path(yaml_path)
    existing_data = {}

    if yaml_file.exists():
        with open(yaml_file, 'r') as f:
            existing_data = yaml.safe_load(f) or {}

    # Create new data structure
    new_data = {
        'google_scholar_id': existing_data.get('google_scholar_id', 'YOUR_GOOGLE_SCHOLAR_ID'),
        'papers': publications
    }

    # Add comment about auto-generation
    comment = """# Publications fetched from Google Scholar
# Last updated: auto-generated by fetch_publications.py
#
# To update, run: python fetch_publications.py
# To add manual entries, edit the 'papers' list below
#
# Note: You can also manually add papers that aren't on Google Scholar

"""

    # Write to file
    with open(yaml_path, 'w') as f:
        f.write(comment)
        yaml.dump(new_data, f, sort_keys=False, allow_unicode=True, default_flow_style=False)

    print(f"\nSuccessfully updated {yaml_path} with {len(publications)} publications!")

def main():
    # Check if data/publications.yaml exists and has a Google Scholar ID
    yaml_path = Path('data/publications.yaml')

    if not yaml_path.exists():
        print("Error: data/publications.yaml not found!")
        print("Please make sure you're running this from the repository root.")
        sys.exit(1)

    # Read the YAML file to get the Google Scholar ID
    with open(yaml_path, 'r') as f:
        data = yaml.safe_load(f)

    scholar_id = data.get('google_scholar_id', '')

    if not scholar_id or scholar_id == 'YOUR_GOOGLE_SCHOLAR_ID':
        print("Error: Please set your google_scholar_id in data/publications.yaml first!")
        print("\nExample:")
        print("  google_scholar_id: 'QGaRpqYAAAAJ'")
        print("\nYou can find your ID in your Google Scholar profile URL:")
        print("  https://scholar.google.com/citations?user=YOUR_ID_HERE")
        sys.exit(1)

    print("Fetching publications from Google Scholar...")
    print("This may take a minute...\n")

    publications = fetch_scholar_publications(scholar_id)

    if publications:
        update_yaml_file(publications, yaml_path)
        print("\nDone! Your publications have been updated.")
        print("Review data/publications.yaml and make any manual adjustments if needed.")
    else:
        print("\nFailed to fetch publications. Please try again later or add them manually.")
        sys.exit(1)

if __name__ == '__main__':
    main()
