#!/usr/bin/env python3
"""Self-host + subset the web fonts the site uses (Font Awesome, Academicons,
Devicon, Inter) so the page makes no third-party requests.

Downloads each upstream font + CSS, keeps only the glyphs actually used (listed
below), subsets the woff2 with fonttools, and writes:
    assets/fonts/*.woff2        subsetted fonts
    assets/css/vendor.css       @font-face + the used icon class rules

Re-run if the icon set changes. Requires: fonttools, curl, network access.
"""
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
FONTS = REPO / "assets" / "fonts"
CSS_OUT = REPO / "assets" / "css" / "vendor.css"
FONTS.mkdir(parents=True, exist_ok=True)

FA = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1"
AI = "https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1"
DV = "https://cdn.jsdelivr.net/gh/devicons/devicon@v2.16.0"
FS = "https://cdn.jsdelivr.net/fontsource/fonts/inter@latest"

# icon class -> (source css url, woff2 url, output woff2 name, css font-family)
FA_BRANDS = ["fa-github", "fa-linkedin", "fa-twitter", "fa-x-twitter"]
FA_SOLID = ["fa-arrow-right", "fa-award", "fa-calendar-day", "fa-chevron-down",
            "fa-clock", "fa-cubes", "fa-envelope", "fa-file-pdf",
            "fa-location-dot", "fa-moon", "fa-rss", "fa-sun"]
AI_ICONS = ["ai-acm", "ai-dblp", "ai-google-scholar", "ai-ieee", "ai-orcid",
            "ai-semantic-scholar"]
DV_ICONS = ["devicon-cplusplus-plain", "devicon-docker-plain",
            "devicon-numpy-plain", "devicon-python-plain",
            "devicon-pytorch-plain", "devicon-tensorflow-original"]


def fetch(url):
    r = subprocess.run(["curl", "-fsSL", url], capture_output=True)
    if r.returncode != 0:
        sys.exit(f"download failed: {url}")
    return r.stdout


def codepoint(css_text, cls):
    """Return (codepoint:int, content_for_css:str) for a `.<cls>:before` rule."""
    # allow grouped/alias selectors between the class and the `{` (FA aliases
    # share one content rule, e.g. `.fa-location-dot:before,.fa-map-...:before{}`)
    m = re.search(
        re.escape("." + cls) + r"::?before[^{]*\{\s*content:\s*\"(.*?)\"\s*;?\s*\}",
        css_text,
    )
    if not m:
        sys.exit(f"no content rule for {cls}")
    raw = m.group(1)
    esc = re.match(r"\\([0-9a-fA-F]+)$", raw)
    cp = int(esc.group(1), 16) if esc else ord(raw)
    return cp, f"\\{cp:x}"


def subset(woff2_bytes, codepoints, out_name):
    src = FONTS / (out_name + ".src.woff2")
    src.write_bytes(woff2_bytes)
    out = FONTS / (out_name + ".woff2")
    unicodes = ",".join(f"U+{c:04X}" for c in codepoints)
    subprocess.run([
        sys.executable, "-m", "fontTools.subset", str(src),
        f"--unicodes={unicodes}", "--flavor=woff2", "--no-hinting",
        "--desubroutinize", f"--output-file={out}",
    ], check=True)
    src.unlink()
    return out.stat().st_size


blocks = ["/* Generated by tools/build_vendor_fonts.py -- do not edit by hand. */"]


def do_icon_font(name, css_url, woff2_url, family, classes, base_rule):
    css = fetch(css_url).decode("utf-8", "replace")
    pairs = [(c, *codepoint(css, c)) for c in classes]
    size = subset(fetch(woff2_url), [cp for _, cp, _ in pairs], name)
    rules = "\n".join(f'.{c}::before{{content:"{content}"}}' for c, _, content in pairs)
    blocks.append(
        f'@font-face{{font-family:"{family}";font-style:normal;'
        f'font-display:swap;src:url("../fonts/{name}.woff2") format("woff2")}}\n'
        f"{base_rule}\n{rules}"
    )
    print(f"  {name}.woff2  {size//1024} KB  ({len(classes)} glyphs)")


print("subsetting icon fonts:")
do_icon_font(
    "fa-brands", f"{FA}/css/all.min.css", f"{FA}/webfonts/fa-brands-400.woff2",
    "Font Awesome 6 Brands", FA_BRANDS,
    '.fab,.fa-brands{font-family:"Font Awesome 6 Brands";font-weight:400;'
    '-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;'
    "font-variant:normal;line-height:1;text-rendering:auto}",
)
do_icon_font(
    "fa-solid", f"{FA}/css/all.min.css", f"{FA}/webfonts/fa-solid-900.woff2",
    "Font Awesome 6 Free", FA_SOLID,
    '.fa,.fas,.fa-solid{font-family:"Font Awesome 6 Free";font-weight:900;'
    '-webkit-font-smoothing:antialiased;display:inline-block;font-style:normal;'
    "font-variant:normal;line-height:1;text-rendering:auto}",
)
do_icon_font(
    "academicons", f"{AI}/css/academicons.min.css", f"{AI}/fonts/academicons.ttf",
    "academicons", AI_ICONS,
    '.ai{font-family:"academicons";-webkit-font-smoothing:antialiased;'
    "display:inline-block;font-style:normal;font-weight:400;line-height:1;"
    "text-rendering:auto}",
)
do_icon_font(
    "devicon", f"{DV}/devicon.min.css", f"{DV}/fonts/devicon.ttf",
    "devicon", DV_ICONS,
    '[class^="devicon-"],[class*=" devicon-"]{font-family:"devicon";'
    "font-style:normal;font-weight:400;line-height:1;display:inline-block;"
    "-webkit-font-smoothing:antialiased;text-rendering:auto}",
)

print("inter (latin subset from fontsource):")
inter_faces = []
for w in (400, 500, 600, 700):
    data = fetch(f"{FS}/latin-{w}-normal.woff2")
    (FONTS / f"inter-{w}.woff2").write_bytes(data)
    inter_faces.append(
        f'@font-face{{font-family:"Inter";font-style:normal;font-weight:{w};'
        f'font-display:swap;src:url("../fonts/inter-{w}.woff2") format("woff2")}}'
    )
    print(f"  inter-{w}.woff2  {len(data)//1024} KB")
blocks.insert(1, "\n".join(inter_faces))

CSS_OUT.write_text("\n".join(blocks) + "\n")
print(f"wrote {CSS_OUT.relative_to(REPO)} ({CSS_OUT.stat().st_size} bytes)")
